class CMSLogin:
    btn_login = '/html/body/div/div/div/a/span[1]'
    #'//*[@id="root"]/div/div/a'
    # btn_login = '//*[@id="app"]/div[1]/div/div/form/div/div/div/div/button'
    txt_email = '//*[@id="email"]'
    btn_sign_in = '//*[@id="signInForm"]/div[4]/button'
    txt_sign_in_email = '//*[@id="identifierId"]'
    btn_next = '//*[@id="identifierNext"]/div/button'
    txt_password = '//*[@id="password"]/div[1]/div/div[1]/input'
    btn_passwordnext = '//*[@id="passwordNext"]/div/button'