class Tutor_Portal:
    # weblink = "https://blc.stage.tllms.com"
    # weblink = "https://tutor.blc.tllms.com"
    txt_email = "//input[@id='email']"
    btn_submit = "//button[@type='submit']"
    txt_google_email = "//input[@type='email']"
    txt_google_password = "//input[@type='password']"
    btn_sign_in = "//button[text()=\"Sign In\"]"
    btn_next = "//span[contains(text(),'Next')]"
    btn_login = "//span[contains(text(),'LOGIN')]"
    btn_join_now = "//div[@class='neo_cl_Button Button--secondary Button--rounded']"
    ele_start_class_mic = "//img[contains(@src,\"/static/media/mic\")]"
    ele_start_class_cam = "//img[contains(@src,\"/static/media/cam\")]"
    ele_setting  = "//img[@alt='settings']"
    ele_av_setting = "//img[@alt='settings']/../following-sibling::span"
    ele_location = "//img[@alt='location']"
    ele_centre_name = "//span[text()=\"[text]\"]"
    ele_room = "//img[@alt='room']"
    ele_room_no = "//img[@alt='room']/following-sibling::span[text()='[text]']"
    ele_no = "('//img[@alt=\'room\']/following-sibling::span[text()= '[text]'])"
    ele_calendar = "//img[@alt='calendar']"
    ele_dateandday = "//span[text()=\"[text]\"]"
    ele_clock= "//img[@alt='clock']"
    ele_sessiontime = "//span[text()=\"[text]\"]"
    # ele_start_class = "//div[@class='container--startClass']/div/span"
    btn_start_class = "//span[text()=\"[text]\"]"
    ele_class_started_xx_hours_back = "//div[@class='container--startClassText']"
    btn_mic_on = "//img[contains(@src,\"/static/media/mic-on\")]"
    btn_mic_off = "//img[contains(@src,\"/static/media/mic-off\")]"
    btn_cam_on = "//img[contains(@src,\"/static/media/cam-on\")]"
    btn_cam_off = "//img[contains(@src,\"/static/media/cam-off\")]"
    btn_av_setting = "//img[@alt='settings']/../following-sibling::span"
    ele_av_setting_text = '/html/body/div[4]/div[3]/div/div[1]/div/li'
    ele_session_slides = '//span[text()="[text1]" and text()="[text2]"]'
    ele_session_plan = '//span[text()="[text1]" and text()="[text2]"]'
    ele_class_log = '//span[text()="[text1]" and text()="[text2]"]'
    ele_class_forum = '//span[text()="[text1]" and text()="[text2]"]'
    ele_student_details = '//span[text()="[text1]" and text()="[text2]"]'
    ele_txt = '//span[text()="[text1]" and text()="[text2]"]'
    btn_session_slide = '//span[text()="[text1]" and text()="[text2]"]'
    btn_class_forum = '//span[text()="[text1]" and text()="[text2]"]'
    ele_video_text = '/html/body/div[4]/div[3]/div/div[2]/section[1]/div[2]/div[2]/div[1]'
    btn_slide_zoom_icon  ="//div[@class = 'slide__slide_number' and text() =\"[text]\"]/../..//div[@class='slide__zoom_action_icon']"
    ele_chapter_name = "//h4[text() = \"[text]\"]"
    ele_subject = '//p[text() = \"[text]\"]'
    ele_syllabus = '//p[text() = \"[text]\"]'
    ele_grade = '//p[text() = \"[text]\"]'
    ele_imag_slide = "//div[@class=\'zoomed-image\']//img[@alt=\'slide\']"
    btn_preview_close = "//div[@class='NeoModal--close']//img[@alt='close']"
    ele_video_slide = "//div[@class= 'playerWrapper']"
    btn_play_and_pause = "//div[@class= 'play-pause']/img"
    btn_pause_video_button = "//img[contains(@src,\"/static/media/playVideo\")]"
    btn_play_video_button = "//img[contains(@src,\"/static/media/pauseVideo\")]"
    btn_video_sound = "//img[contains(@src,\"/static/media/videoSound\")]"
    btn_mute_video ="//img[contains(@src,\"/static/media/muteVideo\")]"
    ele_global_control_text = "//div[text() = \"[text]\"]"
    ele_bg_video_screen = '//div[@class="stream--overlay"]'
    ele_tutor_card = "//div[@class = 'tutorCard--overlay tutorCard--status']"
    ele_end_class = "//span[text()=\"[text]\"]"
    ele_timer = "//div[@class='topContainer--timer']"
    btn_tutor_card_mic_on = "//div[@class = 'tutorCard--icon tutorCard--grey_icon']/img[contains(@src,\"/static/media/mic-on\")]"
    btn_tutor_card_mic_off = "//div[@class = 'tutorCard--icon tutorCard--grey_icon tutorCard--red_icon']/img[contains(@src,\"/static/media/mic-off\")]"
    btn_tutor_card_cam_on = "//div[@class = 'tutorCard--icon tutorCard--grey_icon']/img[contains(@src,\"/static/media/cam-on\")]"
    btn_tutor_card_cam_off = "//div[@class = 'tutorCard--icon tutorCard--grey_icon tutorCard--red_icon']/img[contains(@src,\"/static/media/cam-off\")]"
    btn_global_student_cam_on = "//div[@class= 'topContainer--action_icon']//img[contains(@src,\"/static/media/cam-on\")]"
    btn_global_student_cam_off = "//div[@class= 'topContainer--action_icon red-bg']//img[contains(@src,\"/static/media/cam-off\")]"
    btn_global_student_mic_on = "//div[@class= 'topContainer--action_icon']//img[contains(@src,\"/static/media/mic-on\")]"
    btn_global_student_mic_off = "//div[@class='topContainer--action_icon red-bg']//img[contains(@src,\"/static/media/mic-off\")]"
    btn_global_student_chat_on = "//div[@class= 'topContainer--action_icon']//img[contains(@src,\"/static/media/chat-on\")]"
    btn_global_student_chat_off = "//div[@class='topContainer--action_icon red-bg']//img[contains(@src,\"/static/media/chat-off\")]"
    ele_global_student_mic_off = "//div[@class='topContainer--action_icon red-bg']//img[contains(@src,\"/static/media/mic-off\")]"
    ele_tutor_card_mic_off = "//div[@class = 'tutorCard--icon tutorCard--grey_icon tutorCard--red_icon']/img[contains(@src,\"/static/media/mic-off\")]"
    ele_focus_mode_on = "//div[@class= 'focus-mode']"
    ele_signal_strength = "//div[@class= 'neo_cl_SignalStrength']"
    btn_session_presentation = "//div[@class = 'slide__slide_number' and text() =\"[text]\"]/../../div/div[2]/div[2]/div"
    btn_toggle_toolbox = "//input[@name= \"toggle-toolbox\"]"
    ele_whiteboard_toolbox = "//*[@class='whiteboard-toolbox--container']//div[@id = 'tool-box']"
    btn_add_slide = "//span[text()='Add New Slide']"
    btn_blank_slide_presentation = "//div[@class = 'slide__slide_name' and text() ='Blank Slide']/../../div/div[2]/div[2]/div"
    btn_selector_icon = "//img[contains(@src,'Toolbar_Selection_Normal')]"
    btn_pen_icon = "//img[contains(@src,'Toolbar_Pen_Normal')]"
    btn_laser_pointer_icon = "//img[contains(@src,'Toolbar_Marker_Normal')]"
    btn_shapes_select = "//img[@alt='subscriptUrl']"
    btn_rectangle_icon = "//img[contains(@src,'Toolbar_Rectangle_Normal')]"
    btn_ellipse_icon = "//img[contains(@src,'Toolbar_Ellipse_Normal')]"
    btn_polygon_icon = "//img[contains(@src,'Toolbar_Polygon_Normal')]"
    btn_star_icon = "//img[contains(@src,'Toolbar_Star_Normal')]"
    btn_line_icon = "//img[contains(@src,'Toolbar_Line_Normal')]"
    btn_text_icon = "//img[contains(@src,'Toolbar_Text_Normal')]"
    btn_eraser_icon = "//img[contains(@src,'Toolbar_Eraser_Normal')]"
    btn_clear_icon = "//img[contains(@src,'Toolbar_Delete_Normal')]"
    btn_color_icon = "//div[@class='tool-box-cell-color']"
    btn_size_icon = "//div[@class='tool-box-cell-font']"
    btn_palette_slider = "//input[@class='palette-stroke-slider']"
    btn_delete_blank_slide = "//div[@class = 'slide__slide_name' and text() ='Blank Slide']/../div[2]"
    btn_whiteboard = "//div[@class ='whiteboardView  ']"
    ele_whiteboard_text = "//div[@class = 'textarea-container']/textarea[text()=\"[text]\"]"
    btn_all_subject_toggle = "//input[@name =/'All Subjects/']"
    btn_attendance_tab = "//button[text()=\"[text]\"]"
    btn_pre_class_tab = "//button[text()=\"[text]\"]"
    btn_last_homework_tab = "//button[text()=\"[text]\"]"
    btn_monthly_test_tab = "//button[text()=\"[text]\"]"
    btn_attendance = "//span[text()=\"[text]\"]"
    ele_attendance_name= "//p[@class ='listHeader--item Attendance history' and text() ='Name']"
    ele_attendance_attendance_history = "//p[@class ='listHeader--item' and text() ='Attendance history']"
    ele_uparrow = "//img[@alt = 'Up Arrow']"
    ele_profile_pic = "//div[@class ='student-info Attendance']/div/img[@alt = 'profile' and contains(text(), initial_avatars)]"
    ele_student_name = "//div[@class ='student-info Attendance']/div[text()='[text]']"
    ele_attended_count = "//div[@class ='student-info Attendance']/div[text()='[text]']/../../div[2]/div/div/div/p/span[@class = 'attended']"
    ele_total_class = "//div[@class ='student-info Attendance']/div[text()='[text]']/../../div[2]/div/div/div/p/span[@class = 'totalClasses']"
    ele_attendance_percentage = "//div[@class ='student-info Attendance']/div[text()='[text]']/../../div[2]/div/div/div/p[contains(@class,'attendance-summary ')]"
    btn_student_join = "//span[contains(text(),'JOIN')]"
    btn_student_join_class = "//span[text()='Join Class']"
    ele_image_slide_presented = "//img[@class = 'presentation__image']"
    ele_video_slide_presented = "// div[ @class ='blcPlayerWrapper']"
    ele_poll_slide_presented = "//div[@class = 'pollSlide']"
    ele_poll_slde_question="//div[@class = 'pollSlide']/div/div[@class='pollSlide__question']"
    ele_poll_slide_questionoption= "//div[@class = 'pollSlide']/div/div[@class='pollSlide__questionOptions']"
    ele_poll_slide_option_header = "//div[@class = 'pollSlide']/div/div[@class='pollSlide__questionOptions']/div[text()='Choose the correct option']"
    ele_poll_slide_option_text = "//div[@class='pollSlide__optionList']/div/div/div[text()='[text]']"
    ele_poll_left_option = "//div[@class = 'presentation__streamView poll-stream-container']"
    ele_poll_tutor_card ="//div[@class = 'presentation__streamView poll-stream-container']/div/div[@class = 'tutorStream']"
    ele_poll_student_card = "//div[@class = 'presentation__streamView poll-stream-container']/div/div[@class = 'studentStream streamHoverContainer']"
    ele_poll_slide_timer = "//span[@class = 'neo-timer__label']"
    btn_fullscreen = "//img[contains(@src,\"/static/media/fullscreenoff\")]"
    ele_presentation_fullscreen = "//div[@class = 'presentation presentation--fullScreenMode']"
    ele_focusmode_icon = "//img[contains(@src,\"/static/media/icon-focus-mode\")]"
    ele_student_focusmode_text = "//div[text()='Focus Mode']"
    ele_focus_mode_toast_title = "//div[text()='Focus mode by tutor will start in 5 seconds']"
    ele_focus_mode_toast_subtitle = "//div[text()='Chat and audio will be disabled']"
    ele_student_mic_off_grey = "//div[@class='iconWrapper icon icon--marginRight mic-Ico icon--off icon--disabled']/img[contains(@src,'/static/media/mic_off_icon_gray')]"
    btn_student_mic_off_grey = "//div[@class ='iconWrapper icon icon--marginRight mic-Ico icon--off icon--lighterBlack']/img[contains(@src,'/static/media/mic_off_icon_gray')]"
    ele_mic_off_grey_icon = "//div[@class ='heading' and text() ='Your tutor has disabled your microphone!']/../preceding-sibling::div"
    ele_mic_off_toast_message_heading = "//div[@class ='heading' and text() ='Your tutor has disabled your microphone!']"
    ele_mic_off_toast_message_text = "//div[@class ='message' and text() ='You can’t turn it on to speak unless your tutor enables it.']"
    btn_student_cam_on = "//img[contains(@src,'/static/media/cam-on')]"
    ele_cam_on_icon = "//div[@class ='heading' and text() ='Your camera is enabled by the tutor.']/../preceding-sibling::div"
    ele_cam_on_toast_message = "//div[@class ='heading' and text() ='Your camera is enabled by the tutor.']"
    btn_handraise = "//img[contains(@src,'/static/media/raisehand')]"
    ele_handraise_icon = "//div[@class = 'bottomContainer__raiseHandText']/../div/img"
    ele_handraise_text = "//div[@class = 'bottomContainer__raiseHandText']"
    btn_handraise_text = "//div[@class = 'bottomContainer__raiseHandText']"
    ele_handsdown_toast_message_heading = "//div[@class = 'heading' and text()='You lowered your hand!']"
    ele_handsdown_toast_message_text = "//div[@class = 'message' and text()='In case if you have any doubt, you can raise hand so that tutor can approach you.']"
    ele_student_card = "//div[@class = 'tuteStreamNameClass neo_cl_StreamCard__name neo_cl_StreamCard__name--black neo_cl_StreamCard__name--advanceLabel' and text()='[text]']"
    ele_student_card_handraise = "//div[@class = 'tuteStreamNameClass neo_cl_StreamCard__name neo_cl_StreamCard__name--black neo_cl_StreamCard__name--advanceLabel' and text()='[text]']/preceding-sibling::div/div[2]/div/div[2]"
    txt_tutor_chat_box = "//input[@placeholder = 'Type something']"
    btn_tutor_chat_send_button = "//div[@class = 'chatInputCard']//*[local-name()='svg' and @class='sendAction']"
    ele_tutor_chat_on_student_chat_box = "//div[@class='text isTutor' and text()='[text]']"
    ele_student_chat_on_tutor_chat_box = "//span[text()='[text1]']/../../../following-sibling::div[@class='messageBox']/div/div[text()='[text2]']"
    btn_student_card_top_right_notification ="//div[@class = 'tuteStreamNameClass neo_cl_StreamCard__name neo_cl_StreamCard__name--black neo_cl_StreamCard__name--advanceLabel' and text()='[text]']/preceding-sibling::div/div[2]/div/div[@class='neo_cl_VideoContainer__overlay_view  neo_cl_VideoContainer__overlay_view--topRight']"
    btn_turn_off_audio_ = "//div[@class ='itemTitle' and text()='Turn Off Audio']"
    btn_turn_off_video_notification = "//div[@class ='itemTitle' and text()='Turn Off Video']"
    btn_turn_on_audio_notification = "//div[@class ='itemTitle' and text()='Request To Turn On Audio']"
    btn_turn_on_video_notification = "//div[@class ='itemTitle' and text()='Turn On Video']"
    ele_turn_off_audio_notification_toast = "//div[@class='heading' and text()='Mute your microphone']"
    btn_turn_off_audio_toast_close = "//div[@class='heading' and text()='Mute your microphone']/../following-sibling::div[@class='close-box']"
    ele_multiAccount = "//div[text()='Multiple Accounts']"
    btn_individual_student_mic_off ="//img[contains(@src,\'/static/media/mic-off\')]"
    btn_reward_close_button = "//img[@alt ='close-button']"
    ele_turn_on_audio_notification_header = "//div[@class = 'heading' and text()='Tutor want to discuss doubt with you.']"
    ele_turn_on_audio_notification_message = "//div[@class = 'message' and text()='Please turn on your microphone']"
    btn_turn_on_audio_notofication_close = "//div[@class = 'infoTip__closeBtn']"
    btn_ask_question_popup = "//div[@class ='itemTitle' and text()='Ask Question']"
    btn_remove_ask_question = "//div[@class ='itemTitle' and text()='Remove from Ask Question']"
    ele_ask_question_notification ="//div[@class = 'message' and text()='Please turn on your microphone  and  camera']"
